### ISSUE TITLE
Old references to `enablestakemining`

### ISSUE THREAD

**Issue by infertux** [decred/dcrstakepool#111]
There are references to `enablestakemining` in _sample-dcrwallet.conf_ and _views/tickets.html_ which is no longer supported since https://github.com/decred/dcrwallet/pull/606.

**Comment by jolan** [comment]
Things got a bit messy because enablestakemining was deprecated in 0.8.2 but the stakepool code at the time of the 0.8.2 release still had a safety check to make sure that was enabled.

Anyway, I was aware of the discrepancy and it will get fixed soon for the next release.  It's nice to have a tracking issue on it though, thank you.
