### ISSUE TITLE
stakepoold hangs on init with debuglevel=RPCC=trace

### ISSUE THREAD

**Issue by jolan** [decred/dcrstakepool#192]
This happens with both master and PR #178.

Master: I see some [TRC] RPCC stakepooluserinfo responses on the console and in the log but they're different.

PR 178: I see the gettickets response printed on the console but not in the log.

So to me it seems like the logger is hanging.

Trace:

http://sprunge.us/MaZY

Possibly related:

I think I have seen occasional hangs with PR #178 without debuglevel=RPCC=trace.  In fact I trurned debuglevel=RPCC=trace on to debug those hangs...  Not sure about master yet.

**Comment by jrick** [comment]
I don't see the log rotator goroutine running in that trace.  If it errored, all writes to the pipe will block because nothing will read them.

Can you try replacing https://github.com/decred/dcrstakepool/blob/e152a59c87319ddc5eac84c94c5e4b34cb8b5b46/backend/stakepoold/log.go#L92 with a function that prints any returned errors from r.Run?

**Comment by jolan** [comment]
Will do.

I reverted to 6980eeff41ce9a7eb0cbaeae7905511595af6005 to test with the old logger and debuglevel=RPCC=trace works OK.

**Comment by jrick** [comment]
possibly fixed by https://github.com/jrick/logrotate/commit/a8596d50eed8e718ac2eda577a0fa956bb1af047
