### ISSUE TITLE
stakepoold panics when wallet goes down and comes back

### ISSUE THREAD

**Issue by chappjc** [decred/dcrstakepool#211]
Maybe when a block goes by while wallet is down.

I don't have the stack trace at the moment, but it happened twice on the current version in the last couple days while I was starting and restarting things.  Fortunately it was a clear issue on [this line](https://github.com/decred/dcrstakepool/blob/master/backend/stakepoold/server.go#L954):

    ctx.wgNeedToVote.Done()

in `processWinningTickets`.  The panic was a negative waitGroup counter.

This seems to be because it always calls `Done()` for the wg even if `Add(1)` is not called because of the conditional [here](https://github.com/decred/dcrstakepool/blob/master/backend/stakepoold/ntfnhandlers.go#L16-L21):

```go
if !ctx.lastBlockSeenHash.IsEqual(blockHash) || ctx.lastBlockSeenHeight != blockHeight {
	hasBeenSeen = false
	ctx.wgNeedToVote.Add(1)
	ctx.lastBlockSeenHash = blockHash
	ctx.lastBlockSeenHeight = blockHeight
}
```

**Comment by jolan** [comment]
My guess -- It is probably the opposite of what you describe.  You may be getting a duplicate notification for a block that has already been voted on when the reconnect happens.  I am very interested to know what exactly is causing it.

If you recall the development of this, this is why I used other concurrency primitives in the beginning to optimize processing of the voting notification.  It is kind of error prone to use waitgroups since we expect to get 1 winning ticket notification per block but we may get 0 or 2.  And then there are the newTickets and spentMissedTickets notifications that get blocked waiting for voting to happen.

The simplest solution is to just sleep in processNewTickets / processSpentMissedTickets for 100-250ms so processWinningTickets has a head start to process and send out the votes.  Then there's no need to use the waitgroup anymore.
