### ISSUE TITLE
Signup takes over 1 minute

### ISSUE THREAD

**Issue by cserb** [decred/dcrstakepool#234]
Signup takes usually more than 1 minute and I had to increase nginx timeout. What could be the reason?

**Comment by detailyang** [comment]
@cserb check you logs, it may do the network io for google recaptcha.

**Comment by cserb** [comment]
@detailyang logs just say:
```
dcrstakepool[5309]: 2017-12-07 16:38:52.930 [INF] CNTL: SignUp POST from 127.0.0.1, email mail@.....com. Inserting.
```
It works for ~2 min and then it continues to work

**Comment by jolan** [comment]
Sounds like a DNS timeout or some sort of network issue.  I remember one admin had a really weird situation where MySQL queries were silently blocking for long periods of time because of an MTU issue between the tunnel and MySQL server.  I would suggest using tcpdump to see if it's something like that.

There's **debuglevel** in dcrstakepool.conf if you still think the issue is in the stake pool code itself.

**Comment by cserb** [comment]
@jolan could it be that the it's not executed in a goroutine but synchronously so that it needs to wait until everything is finished?
