### ISSUE TITLE
external smtp server with self signed certs

### ISSUE THREAD

**Issue by karamble** [decred/dcrstakepool#316]
`[ERR] CNTL: error sending password reset email tls: either ServerName or InsecureSkipVerify must be specified in the tls.Config`

getting this error lately.

should have ability to specify initialization of crypto/tls config:
https://github.com/decred/dcrstakepool/blob/179569cfb5ec3d93a188e379bc509157e6169b10/controllers/main.go#L158-L162

**Comment by chappjc** [comment]
I've had to make this change too

**Comment by chappjc** [comment]
Specifically,

```go
tlsConfig := tls.Config{
    InsecureSkipVerify: true,
}
```

**Comment by kiahmed** [comment]
I ran in with the above modification in earlier version but new version dont even have this tls config in main file but during sending email it still complains, so where to fix it now?
error sending password reset email tls: either ServerName or InsecureSkipVerify must be specified in the tls.Config

**Comment by isuldor** [comment]
@kiahmed looks like it's in been refactored over to `email/email.go`

**Comment by jrick** [comment]
InsecureSkipVerify is not a fix.  Never use this.

**Comment by chappjc** [comment]
Not unless you want a mitm attack.  It's only a workaround for local servers, and only until a proper fix (specifying the cert) is in place.

**Comment by jrick** [comment]
Local as in loopback, or on the same private network?

**Comment by chappjc** [comment]
localhost.

**Comment by jrick** [comment]
TLS is pointless on loopback.

**Comment by kiahmed** [comment]
well, then where do you mention the certificate ..dont see any option for dcrstakepool to pass

**Comment by jrick** [comment]
If it is only and always connecting through loopback, it would be reasonable to remove TLS from the connection entirely.  Otherwise, you can add the certificate to the system's trust store rather than manually specifying it in code or config.

I would recommend forgoing the self-signed certs entirely though and using a tool such as [mkcrt](https://github.com/FiloSottile/mkcert) to create your own private CA which can sign any of your server's presented certificates.

**Comment by chappjc** [comment]
@jrick Consider you are running some kind of email bridge that does not have a no-TLS option, which I can only tell you is the case since I don't want to give specifics for all the world to know.

@kiahmed It is not an option presently.  Issue: https://github.com/decred/dcrstakepool/issues/341  But as jrick said, you can try to add the servers TLS certificate in your system's trust store.

**Comment by dajohi** [comment]
example: https://github.com/decred/politeia/blob/512ea07671918b692c0f1346a3c15ef4ad8745cc/politeiawww/config.go#L822-L844
