### ISSUE TITLE
Design REST API for external integration.

### ISSUE THREAD

**Issue by marcopeereboom** [decred/dcrstakepool#34]
We want to be able to integrate stakepools with, for example, Paymetheus.  The idea is that we want to prompt the user to enter username, password and stakepool and Paymetheus fully automates the process.

This ticket's end-game is to have a spec that allows full integration between stakepools and external apps.  Care must be taken to ensure security is a built-in feature.

General features/security concerns:
- [ ] Rate limiting to prevent abuse

Minimum required RPCs:
- [ ] Create account
- [ ] Login
- [ ] Obtain script
- [ ] Status
- [ ] Stats
- [ ] Logout

Discuss the following RPCs:
- [ ] Delete account
- [ ] Reset password

**Comment by Dyrk** [comment]
It doesn't work for me. Neither with the test script `apiClientExample.sh`, nor with my own Ajax requests to the API.
The responses are always `Invalid Csrf Token` or `Invalid Csrf Header`. Any hint how to fix it? I've tried already set the ["X-CSRF-Token" header](https://github.com/goji/csrf#json-responses) and many other things, but didn't find a working solution yet.

In the browser it works ok, so the problem is only with XHR / curl requests.
https://stakepool.dcrstats.com/api/v0.1/stats

**Comment by Dyrk** [comment]
Oh, finally found it in the [config](https://github.com/decred/dcrstakepool/blob/master/config.toml.example#L20) file lol.
The correct (default) header name is `X-XSRF-TOKEN`.
