### ISSUE TITLE
Add errors package

### ISSUE THREAD

**Issue by JoeGruffins** [decred/dcrstakepool#518]
This is just a suggestion to get our errors more organized.  There are many times when we log errors twice, probably some places where errors aren't logged at all.  We could start organizing them better with a scheme descriped here: https://dave.cheney.net/2016/04/27/dont-just-check-errors-handle-them-gracefully
This is also something that is being done in dcrwallet: https://github.com/decred/dcrwallet/tree/master/errors

**Comment by JoeGruffins** [comment]
A valuable opinion on the topic 
https://matrix.to/#/!HEeJkbPRpAqgAwhXWO:decred.org/$156882789034142KmUIm:decred.org
tldr: It's too complex.

**Comment by jholdstock** [comment]
Because we support both the current and the previous versions of Go, dcrwallet has had to include a shim to make use of the new error features in 1.13 and still maintain compatibility with 1.12

https://github.com/decred/dcrwallet/blob/4bd4faa11f9b7ad0cb82a2107d22e7f1d023803b/errors/errors.go#L5-L7

We won't need to include this shim if we wait until Go 1.14 is released, which should make implementing your suggestion slightly less painful.
